### ISSUE TITLE
npm ERR! www@1.0.0 build: `make build`

### ISSUE THREAD

**Issue by dellbeat** [LLK/scratch-www#1903]
I had clone this git to my server and want to run it.
But i have a problem when I run "npm run build" command.
Here are the tips.

make[1]: Leaving directory `/root/scratch-www'
make[1]: Entering directory `/root/scratch-www'
NODE_OPTIONS=--max_old_space_size=8000 ./node_modules/.bin/webpack --bail
make[1]: *** [webpack] Killed
make[1]: Leaving directory `/root/scratch-www'
make: *** [build] Error 2
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! www@1.0.0 build: `make build`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the www@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-30T03_33_35_857Z-debug.log

Here is the log file

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.1.0
3 info using node@v6.14.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle www@1.0.0~prebuild: www@1.0.0
6 info lifecycle www@1.0.0~build: www@1.0.0
7 verbose lifecycle www@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle www@1.0.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/scratch-www/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle www@1.0.0~build: CWD: /root/scratch-www
10 silly lifecycle www@1.0.0~build: Args: [ '-c', 'make build' ]
11 silly lifecycle www@1.0.0~build: Returned: code: 2  signal: null
12 info lifecycle www@1.0.0~build: Failed to exec build script
13 verbose stack Error: www@1.0.0 build: `make build`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:920:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
14 verbose pkgid www@1.0.0
15 verbose cwd /root/scratch-www
16 verbose Linux 3.10.0-693.2.2.el7.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v6.14.2
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 2
22 error www@1.0.0 build: `make bu ild`
22 error Exit status 2
23 error Failed at the www@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

### Operating System and Browser

Operating System:CentOS 7.4 64Bit

I hope someone can give me advice , thanks!

**Comment by thisandagain** [comment]
What version of Node and NPM are you using?

**Comment by dellbeat** [comment]
the version of Node is v6.14.2

**Comment by dellbeat** [comment]
the version of Node is v6.14.2 ,the version of NPM is 6.1.0

**Comment by thisandagain** [comment]
Could you try using Node 8.X and NPM 6.X and giving it another try?

**Comment by dellbeat** [comment]
OK, I will try it.

**Comment by cugliang** [comment]
I have the same problem.Do you solve the problem pls?

**Comment by coderwang1** [comment]
I have the same problem.

**Comment by JoelGritter** [comment]
@coderwang1 @cugliang Have you tried updating Node and NPM?

**Comment by coderwang1** [comment]
yes.
 node : v8.9.2    
 npm : 6.1.0

**Comment by JoelGritter** [comment]
@coderwang1 What OS are you using?

**Comment by coderwang1** [comment]
@JoelGritter  Win10

**Comment by JoelGritter** [comment]
@coderwang1 and you ran `npm install` before `npm run build`?

**Comment by coderwang1** [comment]
@JoelGritter   yes  . I run   npm install  before .

**Comment by KevinGaoZF** [comment]
I have the same problem. can help me?

os: win10 x64 
node : v11.6.0
npm : 6.5.0-next.0

LOG INFO------------
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\DevSoft\\NodeJs\\node.exe',
1 verbose cli   'D:\\DevSoft\\NodeJs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.5.0-next.0
3 info using node@v11.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle www@1.0.0~prebuild: www@1.0.0
6 info lifecycle www@1.0.0~build: www@1.0.0
7 verbose lifecycle www@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle www@1.0.0~build: PATH: D:\DevSoft\NodeJs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\DevSapce\Scratch\scratch-www-develop\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Java\jdk1.8.0_181\bin;C:\Program Files\Java\jdk1.8.0_181\jre\bin;D:\DevSoft\SVN\bin;D:\DevSoft\MySQL\bin;D:\DevSoft\Git\cmd;D:\DevSoft\apache-maven-3.5.4\bin;D:\DevSoft\apache-maven-3.5.4\bin;D:\DevSoft\NodeJs\;C:\Users\Surface\AppData\Local\Microsoft\WindowsApps;;D:\Fiddler;C:\Users\Surface\AppData\Roaming\npm
9 verbose lifecycle www@1.0.0~build: CWD: D:\DevSapce\Scratch\scratch-www-develop
10 silly lifecycle www@1.0.0~build: Args: [ '/d /s /c', 'make build' ]
11 silly lifecycle www@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle www@1.0.0~build: Failed to exec build script
13 verbose stack Error: www@1.0.0 build: `make build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\DevSoft\NodeJs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:188:13)
13 verbose stack     at ChildProcess.<anonymous> (D:\DevSoft\NodeJs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:188:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid www@1.0.0
15 verbose cwd D:\DevSapce\Scratch\scratch-www-develop
16 verbose Windows_NT 10.0.17134
17 verbose argv "D:\\DevSoft\\NodeJs\\node.exe" "D:\\DevSoft\\NodeJs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v11.6.0
19 verbose npm  v6.5.0-next.0
20 error code ELIFECYCLE
21 error errno 1
22 error www@1.0.0 build: `make build`
22 error Exit status 1
23 error Failed at the www@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by emmaccacca** [comment]
same problem.
Tried some times and build successfully. But I encountered error when run 'npm start'.
![image](https://user-images.githubusercontent.com/5310448/51720892-65fa7800-208a-11e9-88d5-28ce242b3d5e.png)

operating system: Linux VM_0_12_centos 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
node: v11.6.0
npm: 6.7.0

**Comment by reginpv** [comment]
I have the same problem

OSX
Node: 10.4.1
NPM: 6.4.1

**Comment by cavern1628** [comment]
I have same problem
OS:linux

NODE: v8.12.0
NPM:v6.4.1

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/node-v8.12.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-117-generic
gyp ERR! command "/opt/node-v8.12.0-linux-x64/bin/node" "/opt/node-v8.12.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/sample/graphgist-cms-master/node_modules/contextify
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:


log

823 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
824 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
825 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
825 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
825 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
825 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
826 verbose stack Error: contextify@0.1.15 install: `node-gyp rebuild`
826 verbose stack Exit status 1
826 verbose stack     at EventEmitter.<anonymous> (/opt/node-v8.12.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
826 verbose stack     at emitTwo (events.js:126:13)
826 verbose stack     at EventEmitter.emit (events.js:214:7)
826 verbose stack     at ChildProcess.<anonymous> (/opt/node-v8.12.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
826 verbose stack     at emitTwo (events.js:126:13)
826 verbose stack     at ChildProcess.emit (events.js:214:7)
826 verbose stack     at maybeClose (internal/child_process.js:915:16)
826 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
827 verbose pkgid contextify@0.1.15
828 verbose cwd /home/sample/graphgist-cms-master
829 verbose Linux 4.4.0-117-generic
830 verbose argv "/opt/node-v8.12.0-linux-x64/bin/node" "/usr/local/bin/npm" "install"
831 verbose node v8.12.0
832 verbose npm  v6.4.1
833 error code ELIFECYCLE
834 error errno 1
835 error contextify@0.1.15 install: `node-gyp rebuild`
835 error Exit status 1
836 error Failed at the contextify@0.1.15 install script.
836 error This is probably not a problem with npm. There is likely additional logging output above.
837 verbose exit [ 1, true ]

**Comment by KevinGaoZF** [comment]
> I have same problem
> OS:linux
> 
> NODE: v8.12.0
> NPM:v6.4.1
> 
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack at ChildProcess.onExit (/opt/node-v8.12.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack at emitTwo (events.js:126:13)
> gyp ERR! stack at ChildProcess.emit (events.js:214:7)
> gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
> gyp ERR! System Linux 4.4.0-117-generic
> gyp ERR! command "/opt/node-v8.12.0-linux-x64/bin/node" "/opt/node-v8.12.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/sample/graphgist-cms-master/node_modules/contextify
> gyp ERR! node -v v8.12.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the contextify@0.1.15 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> 
> log
> 
> 823 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
> 824 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 825 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS: darwin
> 825 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch: any
> 825 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS: linux
> 825 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
> 826 verbose stack Error: contextify@0.1.15 install: `node-gyp rebuild`
> 826 verbose stack Exit status 1
> 826 verbose stack at EventEmitter. (/opt/node-v8.12.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
> 826 verbose stack at emitTwo (events.js:126:13)
> 826 verbose stack at EventEmitter.emit (events.js:214:7)
> 826 verbose stack at ChildProcess. (/opt/node-v8.12.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 826 verbose stack at emitTwo (events.js:126:13)
> 826 verbose stack at ChildProcess.emit (events.js:214:7)
> 826 verbose stack at maybeClose (internal/child_process.js:915:16)
> 826 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> 827 verbose pkgid contextify@0.1.15
> 828 verbose cwd /home/sample/graphgist-cms-master
> 829 verbose Linux 4.4.0-117-generic
> 830 verbose argv "/opt/node-v8.12.0-linux-x64/bin/node" "/usr/local/bin/npm" "install"
> 831 verbose node v8.12.0
> 832 verbose npm v6.4.1
> 833 error code ELIFECYCLE
> 834 error errno 1
> 835 error contextify@0.1.15 install: `node-gyp rebuild`
> 835 error Exit status 1
> 836 error Failed at the contextify@0.1.15 install script.
> 836 error This is probably not a problem with npm. There is likely additional logging output above.
> 837 verbose exit [ 1, true ]

I am having this problem on Windows 10, then I switched to Linux and then came back again, and it succeeded.

**Comment by huangjide** [comment]
I have the same problem.
OS:mac

NODE: v10.11.0
NPM:v6.9.0

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.11.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.9.0
3 info using node@v10.11.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle www@1.0.0~prebuild: www@1.0.0
6 info lifecycle www@1.0.0~build: www@1.0.0
7 verbose lifecycle www@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle www@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/derek/gitProjects/scratch/scratch-www/node_modules/.bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/Users/derek/Library/apache-maven-3.5.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/derek/Library/Android/sdk/tools:/Users/derek/Library/Android/sdk/platform-tools
9 verbose lifecycle www@1.0.0~build: CWD: /Users/derek/gitProjects/scratch/scratch-www
10 silly lifecycle www@1.0.0~build: Args: [ '-c', 'make build' ]
11 silly lifecycle www@1.0.0~build: Returned: code: 2  signal: null
12 info lifecycle www@1.0.0~build: Failed to exec build script
13 verbose stack Error: www@1.0.0 build: `make build`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid www@1.0.0
15 verbose cwd /Users/derek/gitProjects/scratch/scratch-www
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/Cellar/node/10.11.0/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v10.11.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 2
22 error www@1.0.0 build: `make build`
22 error Exit status 2
23 error Failed at the www@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by jinjiangz** [comment]
I have the same problem.
OS:mac

NODE: v10.15.3
NPM:v6.4.1

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle www@1.0.0~prebuild: www@1.0.0
6 info lifecycle www@1.0.0~build: www@1.0.0
7 verbose lifecycle www@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle www@1.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\scratch-www\node_modules\.bin;C:\cygwin64\usr\local\bin;C:\cygwin64\bin;C:\Program Files (x86)\NetSarang\Xshell 6;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Microsoft MPI\Bin;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\dotnet;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\TortoiseSVN\bin;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Java\jdk1.8.0_162\bin;C:\Program Files\Java\jdk1.8.0_162\jre\bin;C:\Services\apache-maven-3.5.3\bin;C:\Program Files\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\nodejs;C:\MinGW\bin;C:\Users\Jinjian\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\JetBrains\PyCharm 2018.3.5\bin;C:\Program Files\JetBrains\WebStorm 2018.3.5\bin;C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.5\bin;C:\Users\Jinjian\AppData\Roaming\npm
9 verbose lifecycle www@1.0.0~build: CWD: D:\scratch-www
10 silly lifecycle www@1.0.0~build: Args: [ '/d /s /c', 'make build' ]
11 silly lifecycle www@1.0.0~build: Returned: code: 2  signal: null
12 info lifecycle www@1.0.0~build: Failed to exec build script
13 verbose stack Error: www@1.0.0 build: `make build`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid www@1.0.0
15 verbose cwd D:\scratch-www
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 2
22 error www@1.0.0 build: `make build`
22 error Exit status 2
23 error Failed at the www@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by reflyhight** [comment]
the same 
node:v8.16.0
npm:6.4.1

**Comment by troyscl** [comment]
I have the same problem.
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.10.1
3 info using node@v10.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle www@1.0.0~prestart: www@1.0.0
6 info lifecycle www@1.0.0~start: www@1.0.0
7 verbose lifecycle www@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle www@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/data/scratch/scratch-www/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle www@1.0.0~start: CWD: /data/scratch/scratch-www
se stack Error: www@1.0.0 start: `make start`
10 silly lifecycle www@1.0.0~start: Args: [ '-c', 'make start' ]
11 silly lifecycle www@1.0.0~start: Returned: code: 2  signal: null
12 info lifecycle www@1.0.0~start: Failed to exec start script
13 verbose stack Error: www@1.0.0 start: `make start`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid www@1.0.0
15 verbose cwd /data/scratch/scratch-www
16 verbose Linux 3.10.0-957.21.3.el7.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v10.16.0
19 verbose npm  v6.10.1
20 error code ELIFECYCLE
21 error errno 2
22 error www@1.0.0 start: `make start`
22 error Exit status 2

**Comment by gh81997167** [comment]
I am the same problem

**Comment by daxdax89** [comment]
Same here.
