### ISSUE TITLE
Preview editor is broken

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#2028]
Going to /preview/editor should show the GUI. Instead something goes wrong:
![image](https://user-images.githubusercontent.com/1512021/44274205-930b4a80-a20f-11e8-9661-051180b1680d.png)

Error log:
```
common.bundle.js:22 TypeError: Cannot read property 'token' of undefined
    at v (preview.bundle.js:146)
    at Function.k [as mapToProps] (preview.bundle.js:146)
    at n (preview.bundle.js:33)
    at Function.n.mapToProps (preview.bundle.js:33)
    at n (preview.bundle.js:33)
    at i (preview.bundle.js:33)
    at preview.bundle.js:33
    at Object.run (preview.bundle.js:33)
    at i.initSelector (preview.bundle.js:33)
    at new i (preview.bundle.js:33)
    at constructClassInstance (common.bundle.js:22)
    at beginWork (common.bundle.js:22)
    at o (common.bundle.js:22)
    at i (common.bundle.js:22)
    at u (common.bundle.js:22)
    at A (common.bundle.js:22)
    at b (common.bundle.js:22)
    at m (common.bundle.js:22)
    at c (common.bundle.js:22)
    at Object.enqueueSetState (common.bundle.js:22)
    at t.o.setState (preview.bundle.js:99)
    at preview.bundle.js:124
e.(anonymous function) @ common.bundle.js:22
common.bundle.js:22 gui Unhandled Error: TypeError: Cannot read property 'token' of undefined    at v (https://scratch.ly/js/preview.bundle.js:146:1436740)    at Function.k [as mapToProps] (https://scratch.ly/js/preview.bundle.js:146:1437003)    at n (https://scratch.ly/js/preview.bundle.js:33:12594)    at Function.n.mapToProps (https://scratch.ly/js/preview.bundle.js:33:12713)    at n (https://scratch.ly/js/preview.bundle.js:33:12576)    at i (https://scratch.ly/js/preview.bundle.js:33:13744)    at https://scratch.ly/js/preview.bundle.js:33:14242    at Object.run (https://scratch.ly/js/preview.bundle.js:33:8170)    at i.initSelector (https://scratch.ly/js/preview.bundle.js:33:10699)    at new i (https://scratch.ly/js/preview.bundle.js:33:9602)    at constructClassInstance (https://scratch.ly/js/common.bundle.js:22:523410)    at beginWork (https://scratch.ly/js/common.bundle.js:22:533743)    at o (https://scratch.ly/js/common.bundle.js:22:545908)    at i (https://scratch.ly/js/common.bundle.js:22:546229)    at u (https://scratch.ly/js/common.bundle.js:22:546467)    at A (https://scratch.ly/js/common.bundle.js:22:550010)    at b (https://scratch.ly/js/common.bundle.js:22:549747)    at m (https://scratch.ly/js/common.bundle.js:22:548875)    at c (https://scratch.ly/js/common.bundle.js:22:548265)    at Object.enqueueSetState (https://scratch.ly/js/common.bundle.js:22:522846)    at t.o.setState (https://scratch.ly/js/preview.bundle.js:99:570)    at https://scratch.ly/js/preview.bundle.js:124:79501Component stack:     in Connect(A)    in div    in m    in div    in m    in div    in m    in div    in m    in MediaQuery    in Ce    in Connect(Ce)    in InjectIntl(Connect(Ce))    in A    in Connect(A)    in t    in Connect(t)    in t    in A    in Unknown    in InjectIntl(Component)    in A    in Connect(A)    in IntlProvider    in r
e.(anonymous function) @ common.bundle.js:22
common.bundle.js:22 
```

There's also a second error, with odd formatting:
```
Uncaught (in promise) Array(1)
0: TypeError: e.assetId.split is not a function
    at https://scratch.ly/js/preview.bundle.js:146:1674317
    at s (https://scratch.ly/js/preview.bundle.js:153:18641)
    at https://scratch.ly/js/preview.bundle.js:153:18791
    at new Promise (<anonymous>)
    at A.value (https://scratch.ly/js/preview.bundle.js:153:18490)
    at s (https://scratch.ly/js/preview.bundle.js:153:16821)
    at https://scratch.ly/js/preview.bundle.js:153:16859message: "e.assetId.split is not a function"stack: "TypeError: e.assetId.split is not a function↵    at https://scratch.ly/js/preview.bundle.js:146:1674317↵    at s (https://scratch.ly/js/preview.bundle.js:153:18641)↵    at https://scratch.ly/js/preview.bundle.js:153:18791↵    at new Promise (<anonymous>)↵    at A.value (https://scratch.ly/js/preview.bundle.js:153:18490)↵    at s (https://scratch.ly/js/preview.bundle.js:153:16821)↵    at https://scratch.ly/js/preview.bundle.js:153:16859"__proto__: Errorlength: 1__proto__: Array(0)
```

**Comment by rschamp** [comment]
It's fixed!

**Comment by benjiwheeler** [comment]
First error described above is fixed (and editor displays!), second is not fixed yet...
