### ISSUE TITLE
After deploying, Fastly config update sometimes fails

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-www#2579]
This has happened a couple of times recently so I wanted to start collecting the errors somewhere.

From https://travis-ci.org/LLK/scratch-www/jobs/474935183
```
/home/travis/build/LLK/scratch-www/bin/configure-fastly.js:268
    if (err) throw new Error(err);
             ^

Error: Failed to update header: Error:  { "errors" : [{ "title" : "Unknown Error Occurred" , "detail" : "Something went wrong - please try again or contact support@fastly.com if it persists" }] } 
    at /home/travis/build/LLK/scratch-www/bin/configure-fastly.js:268:20
    at /home/travis/build/LLK/scratch-www/node_modules/async/lib/async.js:52:16
    at /home/travis/build/LLK/scratch-www/node_modules/async/lib/async.js:570:21
    at /home/travis/build/LLK/scratch-www/node_modules/async/lib/async.js:167:37
    at /home/travis/build/LLK/scratch-www/bin/configure-fastly.js:171:29
    at /home/travis/build/LLK/scratch-www/node_modules/async/lib/async.js:52:16
    at done (/home/travis/build/LLK/scratch-www/node_modules/async/lib/async.js:241:17)
    at /home/travis/build/LLK/scratch-www/node_modules/async/lib/async.js:44:16
    at /home/travis/build/LLK/scratch-www/bin/configure-fastly.js:149:37
    at /home/travis/build/LLK/scratch-www/node_modules/async/lib/async.js:52:16
make[1]: *** [sync-fastly] Error 1
make[1]: Leaving directory `/home/travis/build/LLK/scratch-www'
make: *** [sync] Error 2
Script failed with status 2

travis_fold:end:dpl.3
failed to deploy
```

**Comment by benjiwheeler** [comment]
Log from 1/11/19:

```
make[1]: Entering directory `/home/travis/build/LLK/scratch-www'
NODE_OPTIONS=--max_old_space_size=8000 node ./bin/configure-fastly.js
/home/travis/build/LLK/scratch-www/bin/configure-fastly.js:268
    if (err) throw new Error(err);
             ^

Error: Failed to update condition "req.url ~ "^/download/?(\?.*)?$"": Error: {"msg":"An error occurred while connecting to the fastly API, please try your request again.","detail":"There has been an internal error, we have been notified"}
    at /home/travis/build/LLK/scratch-www/bin/configure-fastly.js:268:20
    at /home/travis/build/LLK/scratch-www/node_modules/async/lib/async.js:52:16
    at /home/travis/build/LLK/scratch-www/node_modules/async/lib/async.js:570:21
    at /home/travis/build/LLK/scratch-www/node_modules/async/lib/async.js:167:37
    at /home/travis/build/LLK/scratch-www/bin/configure-fastly.js:109:29
    at /home/travis/build/LLK/scratch-www/node_modules/async/lib/async.js:52:16
    at done (/home/travis/build/LLK/scratch-www/node_modules/async/lib/async.js:241:17)
    at /home/travis/build/LLK/scratch-www/node_modules/async/lib/async.js:44:16
    at /home/travis/build/LLK/scratch-www/bin/configure-fastly.js:104:33
    at Fastly.<anonymous> (/home/travis/build/LLK/scratch-www/bin/lib/fastly-extended.js:75:24)
make[1]: *** [sync-fastly] Error 1
make[1]: Leaving directory `/home/travis/build/LLK/scratch-www'
make: *** [sync] Error 2
Script failed with status 2

travis_fold:end:dpl.3
```

**Comment by benjiwheeler** [comment]
Also, on 8/2/2019 @paulkaplan had this error:

![image](https://user-images.githubusercontent.com/3431616/88943842-fbfff780-d259-11ea-80dd-04cd5d6269e9.png)

**Comment by benjiwheeler** [comment]
On 7/30/2020 I ran into an error twice where configure-fastly.js failed with a timeout error, after first successfully configuring a new VCL using the fastly API (VCL is present on fastly, just not set to active)
