### ISSUE TITLE
Tests failed with error "cannot find scratch-l10n"

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#3159]
On a PR, this build failed: https://travis-ci.org/LLK/scratch-www/builds/560788528?utm_source=github_status&utm_medium=notification

The error message was 

```
Error: Cannot find module 'scratch-l10n'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/LLK/scratch-www/bin/build-locales:37:19)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

**Comment by benjiwheeler** [comment]
This occurred again at https://travis-ci.org/LLK/scratch-www/builds/566265174?utm_source=github_status&utm_medium=notification

```
Error: Cannot find module 'scratch-l10n'
526    at Function.Module._resolveFilename (module.js:548:15)
527    at Function.Module._load (module.js:475:25)
528    at Module.require (module.js:597:17)
529    at require (internal/module.js:11:18)
530    at Object.<anonymous> (/home/travis/build/LLK/scratch-www/bin/build-locales:37:19)
531    at Module._compile (module.js:653:30)
532    at Object.Module._extensions..js (module.js:664:10)
533    at Module.load (module.js:566:32)
534    at tryModuleLoad (module.js:506:12)
535    at Function.Module._load (module.js:498:3)
```
