### ISSUE TITLE
Unable to run the project locally, 'npm start'

### ISSUE THREAD

**Issue by sumanthyedoti** [LLK/scratch-www#3494]
### 'npm install'
python error
```
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/y_sumanth/dev/react/scratch-www/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/y_sumanth/dev/react/scratch-www/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/y_sumanth/dev/react/scratch-www/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/y_sumanth/dev/react/scratch-www/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/y_sumanth/dev/react/scratch-www/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/y_sumanth/dev/react/scratch-www/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21)
```
--
```
1 error generated.
make: *** [Release/obj.target/binding/src/create_string.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/y_sumanth/dev/react/scratch-www/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/12.7.0/bin/node" "/Users/y_sumanth/dev/react/scratch-www/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/y_sumanth/dev/react/scratch-www/node_modules/node-sass
gyp ERR! node -v v12.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.6.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.6.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/y_sumanth/.npm/_logs/2019-10-31T04_37_48_494Z-debug.log
```

### npm start
node-sass error
```
ERROR in ./~/css-loader!./~/postcss-loader/lib?{}!./~/sass-loader/lib/loader.js!./src/main.scss
Module build failed: Error: Cannot find module 'node-sass'
```
--
```
ℹ ｢wdm｣: Failed to compile.
```
### Operating System and Browser

_Mac OS 10.14.6; Chrome 78_

**Comment by apple502j** [comment]
Do you have python2?

**Comment by y-sumanth** [comment]
@apple502j 
yes, I have. I tired aliasing`python` command to `python2` also

**Comment by apple502j** [comment]
is it on PATH?

**Comment by ZQ-jhon** [comment]
same issue
