### ISSUE TITLE
Build failure on Node 10+, windows 10

### ISSUE THREAD

**Issue by peabrainiac** [LLK/scratch-www#4152]
Running `npm install` in this repository results in an error on my machine:
![grafik](https://user-images.githubusercontent.com/43812953/85923549-2f7ee900-b88c-11ea-8719-50a48d2821b3.png)

From the mentioned error log:
```
...
2179 silly saveTree | `-- yargs@6.6.0
2179 silly saveTree |   +-- camelcase@3.0.0
2179 silly saveTree |   +-- cliui@3.2.0
2179 silly saveTree |   | `-- string-width@1.0.2
2179 silly saveTree |   |   `-- is-fullwidth-code-point@1.0.0
2179 silly saveTree |   +-- string-width@1.0.2
2179 silly saveTree |   `-- yargs-parser@4.2.1
2179 silly saveTree |     `-- camelcase@3.0.0
2179 silly saveTree `-- xhr@2.2.0
2179 silly saveTree   `-- once@1.1.1
2180 warn acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
2181 warn ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
2182 warn eslint-config-scratch@5.0.0 requires a peer of babel-eslint@^8.0.1 but none is installed. You must install peer dependencies yourself.
2183 warn eslint-config-scratch@5.0.0 requires a peer of eslint@^4.0 but none is installed. You must install peer dependencies yourself.
2184 warn file-loader@4.0.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
2185 warn ink@2.3.0 requires a peer of react@>=16.8.0 but none is installed. You must install peer dependencies yourself.
2186 warn url-loader@2.3.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
2187 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules\tap\node_modules\fsevents):
2188 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
2189 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
2189 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
2189 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
2189 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
2190 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
2191 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
2192 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
2192 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
2192 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
2192 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
2193 verbose stack Error: node-sass@4.6.1 postinstall: `node scripts/build.js`
2193 verbose stack Exit status 1
2193 verbose stack     at EventEmitter.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
2193 verbose stack     at EventEmitter.emit (events.js:198:13)
2193 verbose stack     at ChildProcess.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
2193 verbose stack     at ChildProcess.emit (events.js:198:13)
2193 verbose stack     at maybeClose (internal/child_process.js:982:16)
2193 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2194 verbose pkgid node-sass@4.6.1
2195 verbose cwd C:\Users\username\Documents\Programme\Scratch\scratch-www
2196 verbose Windows_NT 10.0.19041
2197 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
2198 verbose node v10.21.0
2199 verbose npm  v6.13.1
2200 error code ELIFECYCLE
2201 error errno 1
2202 error node-sass@4.6.1 postinstall: `node scripts/build.js`
2202 error Exit status 1
2203 error Failed at the node-sass@4.6.1 postinstall script.
2203 error This is probably not a problem with npm. There is likely additional logging output above.
2204 verbose exit [ 1, true ]
```

I've tried using different versions of node instead, but the result was always the same. What could be the problem here, and how can I get this to work?

### Steps to Reproduce
```
git pull
npm install
```

### Operating System and Browser

Windows 10 Build 19041.329
Node 10.21.0, 12.18.1, 13.14.0 and 14.4.0

**Comment by apple502j** [comment]
It seems like Visual Studio 2019 is required?

**Comment by peabrainiac** [comment]
Maybe? I already have the Visual Studio 2019 Build Tools installed though, and that's also what the path in the error message points to, so I'm guessing the problem lies somewhere else.

**Comment by peabrainiac** [comment]
I've read multiple threads now (most importantly, [this one](https://github.com/nodejs/node-gyp/issues/1864)) that suggest that node-gyp is using the wrong version of MSBuild, and should be using the one at `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` instead (which I've verified exists on my machine); however, none of the methods described there to change which version is used seem to work for me, from creating environment variables  or changing how node is configured to editing the module code myself.
I'm not quite sure if this is even the right place to ask at this point; it may be a problem with how node-gyp is configured here, or a problem with node-gyp itself.
