### ISSUE TITLE
Flaky test: sign-in-and-out.test.js

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-www#4378]
Worked after I ran it a second time

FAIL test/integration/sign-in-and-out.test.js (71.647s)
  www-integration sign-in-and-out
    sign in
      ✓ sign in on www (13154ms)
      ✓ sign in on scratchr2 (13943ms)
    sign out
      ✕ sign out on www (25344ms)
      ✓ sign out on scratchr2 (10883ms)
  ● www-integration sign-in-and-out › sign out › sign out on www
    TimeoutError: findByXpath timed out for path: //li[@class="link right login-item"]
    Wait timed out after 20811ms
      91 | 
      92 |     findByXpath (xpath, timeoutMessage = `findByXpath timed out for path: ${xpath}`) {
    > 93 |         return this.driver.wait(until.elementLocated(By.xpath(xpath)), DEFAULT_TIMEOUT_MILLISECONDS, timeoutMessage)
         |                            ^
      94 |             .then(el => (
      95 |                 this.driver.wait(el.isDisplayed(), DEFAULT_TIMEOUT_MILLISECONDS, `${xpath} is not visible`)
      96 |                     .then(() => el)
      at node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at node_modules/selenium-webdriver/lib/promise.js:2927:27
      at node_modules/selenium-webdriver/lib/promise.js:668:7
      From: Task: findByXpath timed out for path: //li[@class="link right login-item"]
      at scheduleWait (node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at SeleniumHelper.wait (test/integration/selenium-helpers.js:93:28)
      at SeleniumHelper.wrapper [as findByXpath] (node_modules/lodash.bindall/index.js:550:15)
      at SeleniumHelper.findByXpath (test/integration/selenium-helpers.js:105:21)
      at wrapper (node_modules/lodash.bindall/index.js:550:15)
      at Object.clickXpath (test/integration/sign-in-and-out.test.js:72:19)

**Comment by BryceLTaylor** [comment]
We should re-open if it stays flaky after fixing all of the tests
