### ISSUE TITLE
npm run build fails on git log -1 --format=%H

### ISSUE THREAD

**Issue by kevster** [LLK/scratch-www#492]
I get the following error when trying to run 'npm run build'. I'm running Node 4.4.4 and git version 2.6.4 (Apple Git-63). Can anyone help? I've tried updating everything, but nothing seems to work. 

```
mycomputer:scratch-www-develop myuser$ npm run build

> www@1.0.0 build /Users/myuser/Dev/scratch-www-develop
> make build

rm -rf ./build
rm -rf ./intl
mkdir -p build
mkdir -p intl
./bin/build-locales intl
./node_modules/.bin/webpack --bail
Error: Command failed: git log -1 --format=%H
fatal: Not a git repository (or any of the parent directories): .git

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)
make[1]: *** [webpack] Error 1
make: *** [build] Error 2

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/myuser/.nvm/versions/node/v5.10.1/bin/node" "/Users/myuser/.nvm/versions/node/v5.10.1/bin/npm" "run" "build"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! www@1.0.0 build: `make build`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the www@1.0.0 build script 'make build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the www package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs www
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls www
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/myuser/Dev/scratch-www-develop/npm-debug.log`
```

**Comment by kevster** [comment]
Seems I made the mistake of downloading the repo through my browser instead of cloning it via

`git clone`

After I did so and ran `npm install` and `npm run build` it works!

**Comment by rschamp** [comment]
This brings up a good point, we should make sure it can build outside of a git working copy.

**Comment by mewtaylor** [comment]
I'm +1 on that, @rschamp. And thanks @kevster for bringing this up!
