### ISSUE TITLE
ValidationError

### ISSUE THREAD

**Issue by sagarbhure** [LLK/scratch-www#5137]
I get the following error after npm run build

ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
    at validate (/root/Videos/Scratch/scratch-www/node_modules/copy-webpack-plugin/node_modules/schema-utils/dist/validate.js:104:11)
    at new CopyPlugin (/root/Videos/Scratch/scratch-www/node_modules/copy-webpack-plugin/dist/index.js:38:31)
    at Object.<anonymous> (/root/Videos/Scratch/scratch-www/webpack.config.js:156:9)
    at Module._compile (/root/Videos/

**Comment by apple502j** [comment]
What version of Node are you using? (scratch-www should be built using Node 12, with Webpack 4.x and copy-webpack-plugin 4.x)

**Comment by sagarbhure** [comment]
@pramodchetri can you please comment

**Comment by PramodChetri** [comment]
node v 15.10.0
webpack  version: 7.6.3
copy webpack plugin version : 7.6.3

**Comment by apple502j** [comment]
scratch-www should be built using Node 12, with Webpack 4.x and copy-webpack-plugin 4.x. Other versions are currently not supported.
