### ISSUE TITLE
npm run build failed

### ISSUE THREAD

**Issue by eric8262** [LLK/scratch-www#660]
make[1]: Entering directory `/opt/scratch/scratch-www'
rm -rf ./build
rm -rf ./intl
mkdir -p build
mkdir -p intl
make[1]: Leaving directory `/opt/scratch/scratch-www'
make[1]: Entering directory `/opt/scratch/scratch-www'
./bin/build-locales intl

fs.js:654
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: EEXIST, file already exists '/opt/scratch/scratch-www/intl'
    at Object.fs.mkdirSync (fs.js:654:18)
    at Object.<anonymous> (/opt/scratch/scratch-www/bin/build-locales:64:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
make[1]: *** [translations] Error 8
make[1]: Leaving directory `/opt/scratch/scratch-www'
make: *** [build] Error 2

**Comment by eric8262** [comment]
My npm version is too low.
